version: '3'
services:
  magic_league_db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: planeswalker
      POSTGRES_PASSWORD: 12345678
    ports:
      - '5432:5432'
    volumes:
      - mtg-league-postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mtg-league
    ports:
      - "3000:3000"
    depends_on:
      - magic_league_db

volumes: 
  mtg-league-postgres:
