module ConfigurationConstants
  VALID_SETS = [
  { code: 'RTR', name: 'Return to Ravnica', symbol: 'ss ss-rtr' },
  { code: 'GTC', name: 'Gatecrash', symbol: 'ss ss-gtc' },
  { code: 'DGM', name: "Dragon’s Maze", symbol: 'ss ss-dgm' },
  { code: 'THS', name: 'Theros', symbol: 'ss ss-ths' },
  { code: 'BNG', name: 'Born of the Gods', symbol: 'ss ss-bng' },
  { code: 'JOU', name: 'Journey into Nyx', symbol: 'ss ss-jou' },
  { code: 'KTK', name: 'Khans of Tarkir', symbol: 'ss ss-ktk' },
  { code: 'FRF', name: 'Fate Reforged', symbol: 'ss ss-frf' },
  { code: 'DTK', name: 'Dragons of Tarkir', symbol: 'ss ss-dtk' },
  { code: 'BFZ', name: 'Battle for Zendikar', symbol: 'ss ss-bfz' },
  { code: 'OGW', name: 'Oath of the Gatewatch', symbol: 'ss ss-ogw' },
  { code: 'SOI', name: 'Shadows over Innistrad', symbol: 'ss ss-soi' },
  { code: 'EMN', name: 'Eldritch Moon', symbol: 'ss ss-emn' },
  { code: 'KLD', name: 'Kaladesh', symbol: 'ss ss-kld' },
  { code: 'AER', name: 'Aether Revolt', symbol: 'ss ss-aer' },
  { code: 'AKH', name: 'Amonkhet', symbol: 'ss ss-akh' },
  { code: 'HOU', name: 'Hour of Devastation', symbol: 'ss ss-hou' },
  { code: 'XLN', name: 'Ixalan', symbol: 'ss ss-xln' },
  { code: 'RIX', name: 'Rivals of Ixalan', symbol: 'ss ss-rix' },
  { code: 'DOM', name: 'Dominaria', symbol: 'ss ss-dom' },
  { code: 'GRN', name: 'Guilds of Ravnica', symbol: 'ss ss-grn' },
  { code: 'RNA', name: 'Ravnica Allegiance', symbol: 'ss ss-rna' },
  { code: 'WAR', name: 'War of the Spark', symbol: 'ss ss-war' },
  { code: 'ELD', name: 'Throne of Eldraine', symbol: 'ss ss-eld' },
  { code: 'THB', name: 'Theros Beyond Death', symbol: 'ss ss-thb' },
  { code: 'IKO', name: 'Ikoria: Lair of Behemoths', symbol: 'ss ss-iko' },
  { code: 'ZNR', name: 'Zendikar Rising', symbol: 'ss ss-znr' },
  { code: 'KHM', name: 'Kaldheim', symbol: 'ss ss-khm' },
  { code: 'STX', name: 'Strixhaven: School of Mages', symbol: 'ss ss-stx' },
  { code: 'AFR', name: 'Adventures in the Forgotten Realms', symbol: 'ss ss-afr' },
  { code: 'MID', name: 'Innistrad: Midnight Hunt', symbol: 'ss ss-mid' },
  { code: 'VOW', name: 'Innistrad: Crimson Vow', symbol: 'ss ss-vow' },
  { code: 'NEO', name: 'Kamigawa: Neon Dynasty', symbol: 'ss ss-neo' },
  { code: 'SNC', name: 'Streets of New Capenna', symbol: 'ss ss-snc' },
  { code: 'DMU', name: 'Dominaria United', symbol: 'ss ss-dmu' },
  { code: 'BRO', name: 'The Brothers\' War', symbol: 'ss ss-bro' },
  { code: 'ONE', name: 'Phyrexia: All Will Be One', symbol: 'ss ss-one' },
  { code: 'MOM', name: 'March of the Machine', symbol: 'ss ss-mom' },
  { code: 'WOE', name: 'Wilds of Eldraine', symbol: 'ss ss-wor' },
  { code: 'LCI', name: 'Lost Caverns of Ixalan', symbol: 'ss ss-lci' },
  { code: 'MKM', name: 'Murders at Karlov Manner', symbol: 'ss ss-mkm' },
  { code: 'OTJ', name: 'Outlaws of Thunder Junction', symbol: 'ss ss-otj' },
  { code: 'BLB', name: 'Bloomburrow', symbol: 'ss ss-blb' },
  { code: 'DSK', name: 'Duskmorn: House of Horrors', symbol: 'ss ss-dsk' },
  { code: 'DFT', name: 'Aetherdrift', symbol: 'ss ss-dft' },
  { code: 'TDM', name: 'Tarkir: Dragonstorm', symbol: 'ss ss-tdm' },
  { code: 'FIN', name: 'Final Fantasy', symbol: 'ss ss-fin' },
  { code: 'EOE', name: 'Edge of Eternities', symbol: 'ss ss-eoe' },
  { code: 'LTR', name: 'The Lord of the Rings: Tales of Middle-earth', symbol: 'ss ss-ltr' },
  { code: 'SPM', name: 'Marvel\'s Spider-Man', symbol: 'ss ss-spm' },
  { code: 'TLA', name: 'Avatar: The Last Airbender', symbol: 'ss ss-tla' },
  { code: 'MH1', name: 'Modern Horizons', symbol: 'ss ss-mh1' },
  { code: 'MH2', name: 'Modern Horizons 2', symbol: 'ss ss-mh2' },
  { code: 'MH3', name: 'Modern Horizons 3', symbol: 'ss ss-mh3' },
  { code: 'TSR', name: 'Time Spiral Remastered', symbol: 'ss ss-tsr' },
  { code: 'DMR', name: 'Dominaria Remastered', symbol: 'ss ss-dmr' },
  { code: 'RVR', name: 'Ravnica Remastered', symbol: 'ss ss-rvr' },
  { code: 'INR', name: 'Innistrad Remastered', symbol: 'ss ss-inr' },
  { code: 'MB1', name: 'Mystery Booster', symbol: 'ss ss-mb1' },
  { code: 'MB2', name: 'Mystery Booster 2', symbol: 'ss ss-mb2' },
  { code: 'CNS', name: 'Conspiracy', symbol: 'ss ss-cns' },
  { code: 'CN2', name: 'Conspiracy: Take the Crown', symbol: 'ss ss-cn2' },
  { code: 'BBD', name: 'Battlebond', symbol: 'ss ss-bbd' },
  { code: 'CMB1', name: 'Mystery Booster Playtest Cards 2019', symbol: 'ss ss-cmb1' },
  { code: 'CMB2', name: 'Mystery Booster Playtest Cards 2021', symbol: 'ss ss-cmb2' },
  { code: 'M10', name: 'Magic 2010', symbol: 'ss ss-m10' },
  { code: 'M11', name: 'Magic 2011', symbol: 'ss ss-m11' },
  { code: 'M12', name: 'Magic 2012', symbol: 'ss ss-m12' },
  { code: 'M13', name: 'Magic 2013', symbol: 'ss ss-m13' },
  { code: 'M14', name: 'Magic 2014', symbol: 'ss ss-m14' },
  { code: 'M15', name: 'Magic 2015', symbol: 'ss ss-m15' },
  { code: 'ORI', name: 'Magic Origins', symbol: 'ss ss-ori' },
  { code: 'M19', name: 'Core Set 2019', symbol: 'ss ss-m19' },
  { code: 'M20', name: 'Core Set 2020', symbol: 'ss ss-m20' },
  { code: 'M21', name: 'Core Set 2021', symbol: 'ss ss-m21' },
  { code: 'FDN', name: 'Foundations', symbol: 'ss ss-fdn' },
  { code: 'STA', name: 'Strixhaven Academy', symbol: 'ss ss-sta' },
  { code: 'BRR', name: 'The Brothers\' War Retro Artifacts', symbol: 'ss ss-brr' },
  { code: 'MUL', name: 'Multiverse Legends', symbol: 'ss ss-mul' },
  { code: 'WOT', name: 'Wilds of Eldraine: Enchanting Tales', symbol: 'ss ss-wot' },
  { code: 'OTP', name: "Breaking News", symbol: 'ss ss-otp' },
  { code: 'DBL', name: 'Innistrad: Double Feature', symbol: 'ss ss-dbl' },
  { code: 'H2R', name: 'Modern Horizons 2 Timeshifts', symbol: 'ss ss-h2r' },
  { code: 'H1R', name: 'Modern Horizons 1 Timeshifts', symbol: 'ss ss-h1r' },
  { code: 'EOS', name: 'Edge of Eternities: Stellar Sights', symbol: 'ss ss-eos' },
  { code: 'FCA', name: 'Final Fantasy: Through the Ages', symbol: 'ss ss-fca' },
  { code: 'SPG', name: 'Special Guests', symbol: 'ss ss-spg' },
  { code: 'BIG', name: 'The Big Score', symbol: 'ss ss-big' },
  { code: 'OGR', name: 'Beyond the Warp', symbol: 'ss ss-mtg' }
].freeze
.freeze
end