default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: mtg_league_test

production:
  <<: *default
  username: <%= ENV['MAGIC_LEAGUE_DATABASE_USERNAME'] %>
  password: <%= ENV['MAGIC_LEAGUE_DATABASE_PASSWORD'] %>
  database: mtg_league_production
