default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

docker: &docker
  <<: *default
  host: <%= ENV['MAGIC_LEAGUE_HOST'] %>
  username: <%= ENV['MAGIC_LEAGUE_DATABASE_USERNAME'] %>
  password: <%= ENV['MAGIC_LEAGUE_DATABASE_PASSWORD'] %>

development:
  <<: *docker
  database: mtg_league_development

test:
  <<: *docker
  database: mtg_league_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
