default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

docker: &docker
  <<: *default
  host: magic_league_db
  username: planeswalker
  password: 12345678

development:
  <<: *docker
  database: mtg_league_development

test:
  <<: *docker
  database: mtg_league_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
